[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && npm run build:server"

[deploy] 
startCommand = "npx tsx server/index.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
